---
- name: Converge
  hosts: all
  tasks:
    - name: "Include wandansible.alertmanager"
      ansible.builtin.include_role:
        name: "wandansible.alertmanager"
      vars:
        alertmanager_github_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"

        alertmanager_config:
          route:
            receiver: dummy

          receivers:
            - name: dummy

          inhibit_rules:
            - source_matchers:
                - severity="critical"
              target_matchers:
                - severity="warning"
              equal: ['alertname']
