---
# {{ ansible_managed }}

{% if alertmanager_config is string %}
{{ alertmanager_config | trim }}
{% elif alertmanager_config is mapping %}
{{ alertmanager_config | to_nice_yaml(indent=2, sort_keys=false) | trim }}
{% endif %}
